apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    p, role:admin, *, *, *, allow

    p, role:dev1-role, applications, *, caine/*, allow
    p, role:dev1-role, repositories, get, *, allow
    p, role:dev1-role, clusters, get, *, allow
    p, role:dev1-role, projects, get, caine, allow
    
    g, dev1, role:dev1-role
    g, admin, role:admin
    
  policy.default: role:none

