apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # Add repositories
  repositories: |
    - url: https://github.com/kims/argocd-poc.git
      name: argocd-poc
      type: git
  url: "localhost:8080"
  # Create user accounts
  accounts.dev1: apiKey, login
