apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externportal-dev
  namespace: argocd
  argocd-image-updater.argoproj.io/image-list: externportal=192.168.49.2:30500/externportal
  argocd-image-updater.argoproj.io/write-back-method: git
  argocd-image-updater.argoproj.io/git-branch: main
spec:
  destination:
    namespace: caine-dev 
    server: https://kubernetes.default.svc
  project: caine
  source:
    path: externportal/
    repoURL: https://github.com/kims/argocd-poc
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-dev.yaml
