apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externportal-test
  namespace: argocd
spec:
  destination:
    namespace: caine-test
    server: https://kubernetes.default.svc
  project: caine
  source:
    path: externportal/
    repoURL: https://github.com/kims/argocd-poc
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-test.yaml
