apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: externportal
  namespace: argocd
spec:
  destination:
    namespace: eniac-dev 
    server: https://kubernetes.default.svc
  project: eniac
  source:
    path: externportal/
    repoURL: https://github.com/kims/argocd-poc
    targetRevision: HEAD
    helm:
      valueFiles:
        - values-poc.yaml

